name: native_flutter_downloader
description: A plugin to download files using the native capabilities.
  URLSession on iOS and DownloadManager on Android
version: 1.2.1
#homepage:
repository: https://github.com/CrackTech-BD/native_flutter_downloader

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.10.0 "

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.cracktech.native_flutter_downloader
        pluginClass: NativeFlutterDownloaderPlugin
      ios:
        pluginClass: NativeFlutterDownloaderPlugin
